### PR TITLE
fixup! fixup! I modified 2 files, deleted .DS_Store file and created …

### PR DESCRIPTION
**Pull request by izumny**
Hi Ian kun

I changed the hyperlink leading to the picture, but I could not figure out why they changed the color of the part you mentioned automatically, and I didn't fix them yet. Do you have any hint for me?

Thanks

### CODE REVIEW

**Comment by iankure** [comment]
oh because the github is indicate those line as a string value, because of quote ('). 

What i would do is, write those comments after the hashtag sign.

for example, this is your original content:

```

$ git clone URL of the file in Github

$ git pull           ----> up to date

$ git checkout -b [branch name]   -----> create branch
   <--> $ git branch -d [branch name]  ----> delete branch

$ git pill

$ atom .
```

Below is what i would do is:
```

# below command cloning the git repo
git clone <<URL of the file in Github>>

# pulling all the data up to date
git pull 

# create the new branch
git checkout -b <<branch name>>

# delete the existing branch 
git branch -d <<branch name>>

# git pill(?) i think this is git pull..?
git pill

# below command will open the code editor. Use the '.' to open all the current directory.
atom .

```


something like that, maybe? 😸

**Comment by ianmiso** [comment]
This is how i write my simple script:

image

I use hashtag sign in front of the each line to explain what this script will do, and such.

**Review by iankure — COMMENTED** [review]
For example, this is how i write my simple script:

image

I use hashtag sign in front of the each line to explain what this script will do, and such.

**Comment by iankure** [comment]
btw the image is populating correctly! yay! 😸 

image

**Comment by izumny** [comment]
Hi Ian kun

I fixed README.md, please check them.

Thanks

**Comment by iankure** [comment]
Oh wait!! This is MD file, so my tips (using the hashtag sign) wont work! 😣 It will work on the coding but not for the MD format...

But you figured it out!!! Great job!!! 😆

**Review by iankure — APPROVED** [review]
Amazing works! 😊😊😊

**Pull request merged**
