### PR TITLE
I deleted syntax ###### Heading level 6

### PR DESCRIPTION
**Pull request by izumny**
Hi Ian kun

I deleted syntax ###### Heading level 6 which did not work as a syntax. Please check it.

Thank you

### CODE REVIEW

**Review by iankure — CHANGES_REQUESTED** [review]
Ohayo Izumi chan,

Looks good, but i see that `.DS_store` file got populated and you are trying to add that file into this repo.

Could you create a `.gitignore` file and add the `.DS_store` file in there?

Another comment,
there is a `README.md` file in this repo.

If you can update the `README.md` file by using the markdown syntax you learned/noted from `whatisreadme.md` file, that would be great.

Basically, you can update the readme.md file by writing what you have learned so far taking the git lesson from me/yamaura sensei by using the markdown format to make the document nice and pretty format.

Please note that you dont have to write what you have learned in English! If Japanese is more convinient for you, please do so! I just want to check your markdown syntax/format, and also hope this new PR will give you a chance to summarize what you have learned for git, and give you a chance to practice using the markdown style. 


Thanks!

**Comment by iankure** [comment]
Also, inside of the `whatisreadme.md`, the picture is not showing up correctly. It can be any picture, but if you can fix it to show the picture correctly, please do so.

Oh... on more thing, the when i click the link, it redirect to the broken website. Please fix the link, for example <<_**chopin - nocturne**_>> and link it to the nocturne youtube video.  

Thank you!

**Comment by izumny** [comment]
Hi Ian kun

I modified 2 files, but README.md is still working on.  Also deleted .DS_Store file but created .gitignore file too.

Thanks

**Comment by iankure** [comment]
Amazing! Everything looks good, but inside of the `.gitignore` file, could you please add the line: `.DS_store` in there? (right now the file is empty inside)

I will explain more about `.gitignore` and hidden files like `.DS_store`, when i meet you this Saturday.

Other than this minor comment, all looks fantastic! Great job!!! 😄

**Comment by iankure** [comment]
Just a friendly reminder, please use `fixup` when you do the git commit for any future fix up submission (if you already did, please disregard this message 😃 )

**Comment by izumny** [comment]
Hi Ian kun

I finished README.md and also added .DS_Store into the .gitignore file. Please check them.

Thank you

**Review by iankure — APPROVED** [review]
Fantastic!!!!! 😆

**Pull request merged**
